### ISSUE TITLE
Output the Organization Data as JSON

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/webcentral-nova#8]
We were looking at introducing GraphQL, but the more we look at it, the less sense it makes for the MVP.  GraphQL may be a requirement for the guides.colorado.edu, announcements.colorad.edu and howto.colorado.edu sites, but for the Directory MVP I think we should just build this using standard REST endpoint like webcentral.colroado.edu/api/v1/orgs with a limited dataset to support real-time search and the full output for each organization at webcentral.colroado.edu/api/v1/orgs/[uuid].

As this is defined, the example JSON in https://github.com/CuBoulder/directory/blob/master/sample_data/directory_10.json needs to be updated so work on the frontend can continue.

## Unanswered Questions

- [ ] Any real advantage to introducing GraphQL now? 
- [ ] What are the performance impact of using GraphQL (with Apolo?) vs. static JSON written to Google's Cloud Storage via Laravel's S3 driver and read from Vue/React/Web Components directly (not through NGINX/PHP).

https://cloud.google.com/storage/docs/access-public-data
https://cloud.google.com/nodejs/getting-started/using-cloud-storage

**Comment by alexfinnarn** [comment]
Here is a link to my investigations so far: https://github.com/CuBoulder/directory/issues/39
